name: Replace Balatro Assets

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Replace Entire Assets, Align & Sign
        run: |
          # 1. 彻底删除 APK 内原有的 assets 文件夹，再将全新的 assets/ 写入
          zip -d balatro.apk "assets/*" || true
          zip -r balatro.apk assets/

          # 2. 定位系统预装的 Android Build Tools
          BUILD_TOOLS=$(ls -d $ANDROID_HOME/build-tools/* | sort -V | tail -n 1)

          # 3. 4 字节对齐
          $BUILD_TOOLS/zipalign -v -p 4 balatro.apk balatro-aligned.apk

          # 4. 固定密钥生成（保证后续版本能覆盖升级）
          keytool -genkeypair -keystore release.keystore \
            -storepass 123456 -alias b -keyalg RSA -validity 10000 \
            -dname "CN=B"

          # 5. v2/v3 完整签名
          $BUILD_TOOLS/apksigner sign \
            --ks release.keystore --ks-pass pass:123456 \
            --out balatro-signed.apk balatro-aligned.apk

      - uses: actions/upload-artifact@v6
        with:
          name: balatro-modified
          path: balatro-signed.apk